### ISSUE TITLE
Fazer com o que o botão Stop (Câmera) volte a funcionar.

### ISSUE THREAD

**Issue by danielfaleiro** [PEQUI-MEC/VSSS-EMC#118]
O botão Stop (Câmera) atualmente está desabilitado porque o seu uso faz o programa dar crash. A proposta é que ele volte a funcionar para que seja possível parar a câmera que será usada pelo programa sem precisar reiniciar o programa.

**Comment by thiagohenrique1** [comment]
Habilitei o Stop e funcionou, mas resulta em segmentation fault em duas ocasiões:
- Quando há dados da calibração de distorções da câmera no quicksave
- Quando é feito um adjust depois de apertar Stop e iniciar a câmera novamente

**Comment by danielfaleiro** [comment]
Resolvido em #163
