### ISSUE TITLE
Implementar PID Test on Click para posição e orientação

### ISSUE THREAD

**Issue by thiagohenrique1** [PEQUI-MEC/VSSS-EMC#127]
Adicionar opção de definir posição e orientação desejada no PID Test on Click. O primeiro clique define posição e o segundo define orientação (orientação é o vetor que aponta para a posição do segundo clique, a partir do primeiro). O movimento deve ocorrer apenas após os dois cliques

**Comment by danielfaleiro** [comment]
Esta ideia é muito boa, porém acho que também devemos manter a opção de selecionar apenas a posição. Ou seja, o usuário não é obrigado a selecionar uma orientação sempre clicando duas vezes. Para isso, a minha ideia é que o usuário faça um clique para selecionar a posição. Se ele manter o clique ativo, ele pode mexer o mouse para ajustar a posição (seria uma reta indicativa que se moveria de forma circular com a posição do mouse). Ao soltar o clique, o robô se moveria com a posição e direção selecionada. A orientação inicial poderia ser o vetor entre o robô e o alvo. Assim, caso o usuário não queira selecionar uma orientação, ele pode clicar e soltar imediatamente. Ou clicar, ajustar a orientação com o mouse e depois soltar para definir uma orientação também.

**Comment by danielfaleiro** [comment]
Novo teste on click feito em #167 e aprimorado em #170, #173 e #185 engoblam a resolução deste issue.
