### ISSUE TITLE
Escolha automática de câmera e xbee, caso haja apenas uma opção

### ISSUE THREAD

**Issue by thiagohenrique1** [PEQUI-MEC/VSSS-EMC#129]
Ao iniciar o programa, ele deve verificar quantas cameras e dispositivos USBs estão conectados. Caso haja apenas uma camera ou um dispositivo USB, eles devem ser selecionados automaticamente como camera e xbee a serem utilizados pelo programa, para agilizar o processo de configuração inicial

**Comment by danielfaleiro** [comment]
XBee automático em #154
